on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: cicd with dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Action step
        uses: ./ # Uses an action in the root directory
