name: image

on:
  push:
    branches: [ cicd ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    container: dockerfile-all:1.0
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1

        - name: Check
          run: ls
