name: image

on:
  push:
    branches: [ cicd ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    # - name: Checkout Project
    #   run: |
    #     pwd
    #     ls
    #     bash ${{github.workspace}}/sijia.sh

    - name: Build
      run: |
        docker stop cicd
        docker rm cicd
        echo ${{github.workspace}}
        docker run -d -t --name cicd --privileged=true -v ${{github.workspace}}:/omniscidb -w /omniscidb dockerfile-all:1.0 bash /omnisci/cicd.sh
        docker logs cicd
        echo "outside info: "
        pwd
        ls

    # - name: Test
    #   working-directory: ${{github.workspace}}/build-${{env.BUILD_TYPE}}
    #   run: ctest -C ${{env.BUILD_TYPE}}


# jobs:
#   login:
#     runs-on: ubuntu-20.04

#     steps:
#     - name: Checkout Project
#       run: |
#         pwd
#         bash ${{github.workspace}}/sijia.sh

# docker rm cicd
# docker run -d --name cicd --privileged=true dockerfile-all:1.0 /usr/sbin/init
# docker exec -i cicd /bin/bash
# hostname



  #   steps:
  #   - name: Login to GitHub Container Registry
  #     uses: docker/login-action@v1
  #     with:
  #       username: "sijialou"
  #       password: "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"

    # container: dockerfile-all:1.0

# uses: actions/checkout@v2