name: image

on:
  push:
    branches: [ cicd ]
  pull_request:
    branches: [ master ]

jobs:
  login:
    runs-on: self-hosted
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        username: "sijialou"
        password: "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"

    # container: dockerfile-all:1.0
    # steps:
    # - name: Checkout Project
    #   uses: actions/checkout@v2

    # - name: Check
    #   run: ls
