name: image

on:
  push:
    branches: [ cicd ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug
  OMNISCIDB_PATH_DOCKER: /workspace/omniscidb
  REPOSITORY_PATH_DOCKER: /root/.m2/repository
  REPOSITORY_PATH: ${{github.workspace}}/../.m2/repository

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: |
        docker stop cicd
        docker rm cicd
        rm -rf ${{env.REPOSITORY_PATH}}
        mkdir -p ${{env.REPOSITORY_PATH}}
        docker run -d -t -p 9901:22 --name cicd --privileged=true -v ${{github.workspace}}:${{env.OMNISCIDB_PATH_DOCKER}} -v ${{env.REPOSITORY_PATH}}:${{env.REPOSITORY_PATH_DOCKER}} -v /workspace/authorized_keys:/root/.ssh/authorized_keys -v /root/.vscode-server:/root/.vscode-server dockerfile-all:1.0 /usr/sbin/init 

# docker run -d -t -p 9901:22 --name cicd --privileged=true -v ${{github.workspace}}:${{env.OMNISCIDB_PATH_DOCKER}} -v ${{env.REPOSITORY_PATH}}:${{env.REPOSITORY_PATH_DOCKER}} -w ${{env.OMNISCIDB_PATH_DOCKER}} dockerfile-all:1.0 /bin/bash
# docker logs cicd

    # - name: Test
    #   working-directory: ${{github.workspace}}/build-${{env.BUILD_TYPE}}
    #   run: ctest -C ${{env.BUILD_TYPE}}    

# cicd.sh

    #     docker stop cicd
    #     docker rm cicd
    #     docker run -t --name cicd --privileged=true -v ${{github.workspace}}:${{env.OMNISCIDB_PATH_DOCKER}} -w ${{env.OMNISCIDB_PATH_DOCKER}} dockerfile-all:1.0 bash cicd.sh
    #     docker logs cicd
    # - name: Cleanup
    #   run: |
    #     docker stop cicd
    #     docker rm cicd

#         bash ./scripts/omnisci-env.sh && bash ./build-omnisci-debug.sh
  
# docker stop cicd
# docker rm cicd
# echo "******************************************************************"
# echo "outside info:"
# ls ${{github.workspace}}


# ls ${{github.workspace}}/build-${{env.BUILD_TYPE}}
        

# jobs:
#   login:
#     runs-on: ubuntu-20.04

#     steps:
#     - name: Checkout Project
#       run: |
#         pwd
#         bash ${{github.workspace}}/sijia.sh

# docker rm cicd
# docker run -d --name cicd --privileged=true dockerfile-all:1.0 /usr/sbin/init
# docker exec -i cicd /bin/bash
# hostname


  #   steps:
  #   - name: Login to GitHub Container Registry
  #     uses: docker/login-action@v1
  #     with:
  #       username: "sijialou"
  #       password: "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"

    # container: dockerfile-all:1.0

# uses: actions/checkout@v2
# docker run -it --name cicd --privileged=true -v /test_cicd/omniscidb:/workspace/omniscidb -v /test_cicd/.m2/repository:/root/.m2/repository -w /workspace/omniscidb dockerfile-all:1.0 bash