name: image

on:
  push:
    branches: [ cicd ]
  pull_request:
    branches: [ master ]

jobs:
  login:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Project
      run: |
        ls
        bash ${{github.workspace}}/sijia.sh

# docker rm cicd
# docker run -d --name cicd --privileged=true dockerfile-all:1.0 /usr/sbin/init
# docker exec -i cicd /bin/bash
# hostname



  #   steps:
  #   - name: Login to GitHub Container Registry
  #     uses: docker/login-action@v1
  #     with:
  #       username: "sijialou"
  #       password: "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"

    # container: dockerfile-all:1.0
    
# 
# 

# uses: actions/checkout@v2