name: image

on:
  push:
    branches: [ cicd ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug
  OMNISCIDB_PATH_DOCKER: /workspace/omniscidb

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: |
        docker stop cicd
        docker rm cicd
        mkdir -p ${{github.workspace}}.m2/repository
        docker run -d --name cicd --privileged=true -v ${{github.workspace}}:${{env.OMNISCIDB_PATH_DOCKER}} -v ${{github.workspace}}/.m2/repository:/root/.m2/repository -w /${{env.OMNISCIDB_PATH_DOCKER}} dockerfile-all:1.0 bash cicd.sh
        docker logs cicd
#         bash ./scripts/omnisci-env.sh && bash ./build-omnisci-debug.sh
    # - name: Cleanup
    #   run: |
    #     docker stop cicd
    #     docker rm cicd

# echo "******************************************************************"
# echo "outside info:"
# ls ${{github.workspace}}


# ls ${{github.workspace}}/build-${{env.BUILD_TYPE}}
        
# - name: Test
#   working-directory: ${{github.workspace}}/build-${{env.BUILD_TYPE}}
#   run: ctest -C ${{env.BUILD_TYPE}}
    
# jobs:
#   login:
#     runs-on: ubuntu-20.04

#     steps:
#     - name: Checkout Project
#       run: |
#         pwd
#         bash ${{github.workspace}}/sijia.sh

# docker rm cicd
# docker run -d --name cicd --privileged=true dockerfile-all:1.0 /usr/sbin/init
# docker exec -i cicd /bin/bash
# hostname



  #   steps:
  #   - name: Login to GitHub Container Registry
  #     uses: docker/login-action@v1
  #     with:
  #       username: "sijialou"
  #       password: "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"

    # container: dockerfile-all:1.0

# uses: actions/checkout@v2



# docker run -it --name cicd --privileged=true -v /test_cicd/omniscidb:/workspace/omniscidb -v /test_cicd/.m2/repository:/root/.m2/repository -w /workspace/omniscidb dockerfile-all:1.0 bash