name: image

on:
  push:
    branches: [ cicd-master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug
  OMNISCIDB_PATH_DOCKER: /workspace/omniscidb
  M2_PATH_DOCKER: /root/.m2
  M2_PATH: ${{github.workspace}}/../.m2

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: |
        docker stop cicd-cider
        docker rm cicd-cider
        rm -rf ${{env.M2_PATH}}/repository
        mkdir -p ${{env.M2_PATH}}/repository
        cp /root/.m2/settings.xml ${{env.M2_PATH}}
        docker run -t -p 9905:22 --name cicd-cider --privileged=true -v ${{github.workspace}}:${{env.OMNISCIDB_PATH_DOCKER}} \
        -v ${{env.M2_PATH}}:${{env.M2_PATH_DOCKER}} -v /workspace/authorized_keys:/root/.ssh/authorized_keys \
        -v /root/.vscode-server:/root/.vscode-server -w ${{env.OMNISCIDB_PATH_DOCKER}} dockerfile-all:1.0 \
        bash cicd.sh
